name = "miro-mcp-server"
main = "src/index.js"
compatibility_date = "2024-06-05"

# Environment variables for development
[env.development]
name = "miro-mcp-server-dev"

[env.production]
name = "miro-mcp-server"
# KV namespaces will be set by GitHub Actions
[[env.production.kv_namespaces]]
binding = "MIRO_TOKENS"
id = "PLACEHOLDER_KV_ID"
preview_id = "PLACEHOLDER_PREVIEW_ID"
